### PR TITLE
Secure mutations of actives and waiters in DatabaseConnectionPool

### PR DESCRIPTION
**Pull request by ffried**
I've had TSan report concurrent access to the two mutable properties of `DatabaseConnectionPool` because `requestConnection` and `releaseConnection` both mutate it but both might be called in concurrently running Futures.
This adds a simple `Lock` (from NIOConcurrencyHelpers) around them.

### CODE REVIEW

**Comment by tanner0101** [comment]
`DatabaseConnectionPool` is not thread-safe by design. Is this happening in a Vapor project?

**Comment by ffried** [comment]
@tanner0101 Yes, it's happening in a  Vapor project. While I understand that most of the classes are not thread safe, the `DatabaseConnectionPool` should probably be. Since it uses a `Worker` that very likely has multiple threads, it's not safe to mutate the two mutable properties without a locking mechanism. Or am I missing something?

**Comment by tanner0101** [comment]
In general, the worker should be a single event loop. For historical reasons, `Worker` needed to be `EventLoopGroup` in Vapor 3. It will be moving to just `EventLoop` in Vapor 4. We should track down what is causing your connection pool to be accessed from more than one thread in your project. That could be a bug in Vapor or a mis-configuration of your project.

**Comment by ffried** [comment]
@tanner0101 In our case, we generate an SQLite database per request (it's a data conversion application).
We create the `SQLiteDatabase` and `DatabaseConnectionPool` ourselves:
```swift
let worker = MultiThreadedEventLoopGroup(numberOfThreads: numberOfThreads)
let dbIOPool = BlockingIOThreadPool(numberOfThreads: 2)
let database = try SQLiteDatabase(storage: .file(path: pathToDBFile), threadPool: dbIOPool)
let dbPool = database.newConnectionPool(config: .init(maxConnections: 1), on: worker)
```
Here, `numberOfThreads` is set to `ProcessInfo.processInfo.activeProcessorCount`. After this code, we first manually run the migrations necessary to create the structure (tables, indices) of the database.

Now consider the following conversion code (`inputModels` being e.g. an Array of some "input model" to convert to a `DBModel` class, which conforms to e.g. `SQLiteModel`):
```swift
let dbModelsFuture = inputModels.map { inputModel in
    dbPool.withConnection {
        DBModel(input: inputModel).save(on: $0)
    }
}.flatten(on: worker)
```

With an 8-core machine, there will be 8 threads working in parallel on the `DatabaseConnectionPool`, right?
Also, we currently have to set `maxConnections` to `1` because of [this bug](https://github.com/vapor/fluent-sqlite/issues/28).

**Comment by tanner0101** [comment]
I see, makes sense that there are race conditions here. You should only pass `EventLoop` (i.e., `group.next()`) to `database.newConnectionPool`. You can create one pool per event loop if you want (that's what Vapor does internally). 

To be extra safe, you should do any configuration work on the event loop as well. You can do this with `EventLoop.submit` like so:

```swift
var it = elg.makeIterator()
while let eventLoop = it.next() {
    eventLoop.submit { 
        let pool = database.newConnectionPool(..., worker: eventLoop)
        ... 
    }
}
```

You may also be interested in https://github.com/vapor/sqlite/pull/50 that was tagged recently. That fixed some concurrency problems with the SQLite package. 

We can continue to discuss a good solution for your use case in this thread or in [Vapor chat](http://vapor.team). But let's close this PR in particular since the connection pool here is not thread safe by design.

**Comment by ffried** [comment]
@tanner0101 I see. Now, my example was simplified. Our application has multiple conversion steps, most of which create (and save) some database model at some point. These steps are all methods of a `Converter` class and run serially (by using the methods as a list of `LazyFuture`s that are executed by calling `syncFlatten(on: worker)`).

So it looks (again simplified) something like this:
```swift
final class Converter {
    let worker: Worker
    let dbPool: DatabaseConnectionPool<SQLiteDatabase>

    init(numberOfThreads: Int, pathToDBFile: String) {
        self.worker = MultiThreadedEventLoopGroup(numberOfThreads: numberOfThreads)
        let dbIOPool = BlockingIOThreadPool(numberOfThreads: 2)
        let database = try SQLiteDatabase(storage: .file(path: pathToDBFile), threadPool: dbIOPool)
        self.dbPool = database.newConnectionPool(config: .init(maxConnections: 1), on: worker)
    }

    func run() -> Future<Void> {
        let steps: [LazyFuture<Void>] = [
            self.step1,
            self.step2,
            /* ... */
        ]
        return prepareDatabase().flatMap { steps.syncFlatten(on: self.worker) }
    }
   
    func prepareDatabase() -> Future<Void> {
        // MigrationConfig.run(on:) is defined in an extension we added and runs all migrations on the database.
        return dbPool.withConnection { MigrationConfig.run(on: $0) }
    }

    func step1() -> Future<Void> {
        return inputModels1.map { input in
            dbPool.withConnection { DBModel1(input: input).save(on: $0) }
        }.flatten(on: worker).transform(to: ())
    }

    func step2() -> Future<Void> {
        return inputModels2.map { input in
            dbPool.withConnection { DBModel2(input: input).save(on: $0) }
        }.flatten(on: worker).transform(to: ())
    }

    /* ... */
}
```

As you can see, the steps simply ask the `dbPool` property for a connection. While I understand the idea behind your example, I don't yet really see how I can adapt it to my problem. If I understand correctly, I would need a *single* `EventLoop` (from the `EventLoopGroup`) in every line I now do `dbPool.withConnection { ... }` and then get its `DatabaseConnectionPool` and then call `withConnection` on it, right?
Since we have a lot of places where we request a database connection, this would blow up our code a lot.
Can we use the `EventLoopGroup` to distribute the iteration of `inputModels` across its `EventLoop`s (similar to `DispatchQueue.concurrentPerform(iterations:execute:)`) and then get one `inputModel` and a `EventLoop` per iteration?
As far as I see it a small extension could turn an `EventLoopGroup` into an infinite sequence of `EventLoop`s (since `next()` always returns another `EventLoop`). We could use this together with `zip` to generate a sequence of `inputModel` and `EventLoop` tuples.
Attaching a `DatabaseConnectionPool` to an `EventLoop` could probably be done using a `ThreadSpecificVariable<DatabaseConnectionPool<SQLiteDatabase>>`... 🤔 

Does this sound right or am I going into a completely wrong direction with this?

**Comment by tanner0101** [comment]
Based on that design, you should have one `Converter` per event loop. Pass a reference to the event loop and the SQLiteDatabase to `Converter.init`, and then it can create and store a connection pool. Then, run the converter (on its single event loop). If you want to run multiple converters across multiple event loops, you can iterate over all the event loops from a group and create one Converter per event loop. Then you will need to figure out how to divide the work between them in a thread safe way (potentially using locks).

**Comment by ffried** [comment]
Thanks for the idea. However, based on our implementation of the `Converter`, having multiple `Converter`s for one conversion would have meant a lot of necessary changes.

I've now built myself an object that manages one main event loop and _n_ worker event loops. Using this object, I've built myself extensions on `Sequence` with `asyncMap` and `asyncFlatMap` implementations. Each iteration is assigned its dedicated `EventLoop` (one of the worker event loops) and with it a dedicated `DatabaseConnectionPool`. Once the work is done, each futures is transferred back to the main event loop (using `hop(to:)`). The resulting list is then flattened on the main event loop, resulting in one `Future` containing the results of all iterations.

With that, we were able to speed up the conversion process by 1,5s (~32%).

**Pull request closed without merging**
